[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "puprisa"
version = "1.0.0"
description = "Pump-Probe Image Stack Analysis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pandas",
  "matplotlib",
  "scikit-image",
  "scipy",
  "tifffile",
  "PySide6"
]

[project.scripts]
puprisa = "puprisa.gui:main"

[tool.setuptools.packages.find]
where = ["src"]
